# Generated by Django 5.0.3 on 2024-03-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='asset',
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
