# Generated by Django 5.0.3 on 2024-03-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_remove_transaction_asset_transaction_asset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='timestamp',
        ),
    ]
