# Generated by Django 5.0.3 on 2024-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_userasset_category_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
